### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by stpnov** [ruabmbua/enet-sys#18]
Please help solve the problem, try different versions of c++

`C:/Users/Alex/.cargo/bin/cargo.exe build --color=always --message-format=json-diagnostic-rendered-ansi --package c_mock --bin c_mock
   Compiling enet-sys v1.0.1
error: failed to run custom build command for `enet-sys v1.0.1`
Caused by:
  process didn't exit successfully: `C:\Users\Alex\Desktop\CMock\target\debug\build\enet-sys-2c37d8d63c9d601a\build-script-build` (exit code: 101)
  --- stderr
  D:/msys64/mingw64/include\stdlib.h:388:47: error: expected ';' after top level declarator
  D:/msys64/mingw64/include\stdlib.h:389:48: error: expected ';' after top level declarator
  D:/msys64/mingw64/include\stdlib.h:396:26: error: expected ';' after top level declarator
  D:/msys64/mingw64/include\stdlib.h:681:69: error: expected ';' after top level declarator
  D:/msys64/mingw64/include\stdlib.h:683:48: error: expected ';' after top level declarator
  D:/msys64/mingw64/include\stdlib.h:684:55: error: expected ';' after top level declarator
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:71:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:133:43: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:163:43: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:193:43: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:220:44: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:243:44: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:264:44: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:291:44: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:314:44: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:335:44: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:356:40: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:377:40: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values)
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:398:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  D:/msys64/mingw64/include\stdlib.h:388:47: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/include\stdlib.h:389:48: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/include\stdlib.h:396:26: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/include\stdlib.h:681:69: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/include\stdlib.h:683:48: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/include\stdlib.h:684:55: error: expected ';' after top level declarator, err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:71:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:133:43: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:163:43: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:193:43: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:220:44: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:243:44: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:264:44: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:291:44: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:314:44: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:335:44: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:356:40: error: passing '__v8qi' (aka 'char') to parameter of incompatible type '__attribute__((__vector_size__(8 * sizeof(char)))) char' (vector of 8 'char' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:377:40: error: passing '__v4hi' (aka 'short') to parameter of incompatible type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values), err: true
  D:/msys64/mingw64/lib/clang/14.0.0/include\mmintrin.h:398:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values), err: true
  fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', C:\Users\Alex\.cargo\registry\src\github.com-1ecc6299db9ec823\enet-sys-1.0.1\build.rs:19:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src/result.rs:1749:5
     3: core::result::Result<T,E>::expect
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src/result.rs:1022:23
     4: build_script_build::main
               at .\build.rs:11:20
     5: core::ops::function::FnOnce::call_once
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Process finished with exit code 101
`

**Comment by ruabmbua** [comment]
Did you manage to solve your problem?

**Comment by stpnov** [comment]
No, I started building on linux
