### ISSUE TITLE
#[derive(Copy, Clone, PartialEq, Eq)] on ENetEventType

### ISSUE THREAD

**Issue by Boscop** [ruabmbua/enet-sys#6]
Please `#[derive(Copy, Clone, PartialEq, Eq)]` on `ENetEventType`.

**Comment by ruabmbua** [comment]
I`ll do it.

**Comment by ruabmbua** [comment]
@Boscop, for me it seems like ENnetEventType is a 
```rust
pub type _ENetEventType = u32;
pub use self::_ENetEventType as ENetEventType;
```

That means, it is essentially a u32, which already implements all the traits.

**Comment by Boscop** [comment]
Ah, sry, I was looking at the old code where `ENetEventType` was an enum (because I had to derive those traits in my fork).

**Comment by Boscop** [comment]
After switching to bindgen generation, did the API of the lib change in any way?
